name = "ipfstesting"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = false
go_version = "1.14"
module_path = "github.com/your/module/name"
exec_pkg = "."

[builders."exec:go"]
enabled = true
module_path = "github.com/your/module/name"

[runners."local:docker"]
enabled = false

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = false

[[testcases]]
name= "test1"
instances = { min = 3, max = 50, default = 3 }
    [testcases.params]
    tempFileDir = { type="string" , desc = "Absolute path to a temp file directory", unit="filepath", default="/home/jake/ipfs-erasure-testing/tmp/"}

    verbose = { type = "boolean", desc = "enable verbose logging", unit = "verbose", default=false }
    tearDown = { type = "boolean", desc = "shut down nodes before test termination. typically set to false during debugging", unit = "boolean", default=true }
    maxRuntimeMinutes = { type = "int", desc = "Maximum Node Runtime", unit = "minutes", default=9 }
    erasureEnabled = { type = "boolean", desc = "Use IPFS-Cluster with Erasure Coding enabled.", unit = "boolean", default=false }
    shutdownProbability = { type = "float", desc = "Shutdown Probability", unit = "percentage", default=0.25 }
    clearIpfsCacheTimeout = { type = "int", desc = "Maximum Node Runtime", unit = "seconds", default=60 }
    filePinTimeout = { type = "int", desc = "Maximum amount of time a file upsert operation can take before failure.", unit = "time_seconds", default=240 }
    fileGetTimeout =  { type = "int", desc = "Maximum amount of time a file retrieval operation can take before failure.", unit = "time_seconds", default=240 }

    fileSizeMB =  { type = "int", desc = "Size of file to upsert", unit = "MB", default=1000 }

[[testcases]]
name= "test2"
instances = { min = 1, max = 50, default = 3 }
    [testcases.params]
    tempFileDir = { type="string" , desc = "Absolute path to a temp file directory", unit="filepath", default="/home/jake/ipfs-erasure-testing/tmp/"}
    verbose = { type = "boolean", desc = "enable verbose logging", unit = "verbose", default=true }

    erasureEnabled = { type = "boolean", desc = "Use IPFS-Cluster with Erasure Coding enabled.", unit = "boolean", default=true }

    shutdownProbability = { type = "float", desc = "Shutdown Probability. 1.0 = 100% chance to shutdown", unit = "decimal", default=1.0 }

    maxRuntimeMinutes = { type = "int", desc = "Maximum Node Runtime", unit = "minutes", default=5 }
    clearIpfsCacheTimeout = { type = "int", desc = "Maximum Node Runtime", unit = "seconds", default=60 }

    filePinTimeout = { type = "int", desc = "Maximum amount of time a file upsert operation can take before failure.", unit = "time_seconds", default=300 }

    maxFiles = { type = "int", desc = "Maximum # of files to upsert.", unit = "time_seconds", default=2 }

    fileSizeMB =  { type = "int", desc = "Size of file to upsert", unit = "MB", default=50 }
    fileSizeIncrease = { type="int", desc="file size scale factor", unit="scale", default=2 }
    fileGetTimeout =  { type = "int", desc = "Maximum amount of time a file retrieval operation can take before failure.", unit = "time_seconds", default=240 }
    tearDown = { type = "boolean", desc = "shut down nodes before test termination. typically set to false during debugging", unit = "verbose", default=true }

[[testcases]]
name= "onlybootstrap"
instances = { min = 1, max = 50, default = 3 }
    [testcases.params]
    tempFileDir = { type="string" , desc = "Absolute path to a temp file directory", unit="filepath", default="/home/jake/ipfs-erasure-testing/tmp/"}
    verbose = { type = "boolean", desc = "enable verbose logging", unit = "verbose", default=true }
    maxRuntimeMinutes = { type = "int", desc = "Maximum Node Runtime", unit = "minutes", default=5 }
    tearDown = { type = "boolean", desc = "shut down nodes before test termination. typically set to false during debugging", unit = "verbose", default=true }
    clearIpfsCacheTimeout = { type = "int", desc = "Maximum Node Runtime", unit = "seconds", default=60 }

